version: '3.7'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: org_hierarchy_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_URL: mysql://root:root@mysql:3306/org_hierarchy_db
      PORT: 3000
    depends_on:
      - mysql

volumes:
  mysql_data:
